import type { GameRecord, ReportData, ReportMeta } from './types';
import type { Aggregates, OpeningRow, WDL } from './aggregate';
import { scorePct, themeLabel, themeUrl } from './aggregate';

const DATA_MARK_START = '<!-- chess-insight:data:v1';
const DATA_MARK_END = 'chess-insight:end -->';

function wdlCells(w: WDL): string {
  return `${w.games} | ${w.wins} | ${w.draws} | ${w.losses} | ${scorePct(w)}%`;
}

function openingTable(rows: OpeningRow[]): string {
  if (!rows.length) return '_No openings with enough games yet (need ≥ 2 games per opening)._\n';
  const lines = [
    '| Opening | ECO | Games | W | D | L | Score | As White | As Black | Avg Accuracy |',
    '|---|---|--:|--:|--:|--:|--:|--:|--:|--:|',
  ];
  for (const o of rows) {
    lines.push(
      `| ${o.family} | ${o.eco || '—'} | ${wdlCells(o)} | ${o.asWhite} | ${o.asBlack} | ${o.avgAccuracy !== null ? o.avgAccuracy + '%' : '—'} |`
    );
  }
  return lines.join('\n') + '\n';
}

export function renderMarkdown(agg: Aggregates, games: GameRecord[], meta: ReportMeta): string {
  const md: string[] = [];
  const a = agg;
  md.push(`# Chess Performance Report — ${meta.username}`);
  md.push('');
  md.push(`_Generated by PawnPrint on ${new Date().toISOString().slice(0, 10)} · ${games.length} games total (${a.analyzedCount} engine/eval-analyzed)_`);
  md.push('');
  md.push('## 1. Overview');
  md.push('');
  md.push('| | Games | W | D | L | Score |');
  md.push('|---|--:|--:|--:|--:|--:|');
  md.push(`| **All games** | ${wdlCells(a.total)} |`);
  md.push(`| As White | ${wdlCells(a.byColor.white)} |`);
  md.push(`| As Black | ${wdlCells(a.byColor.black)} |`);
  md.push('');
  if (a.overallAccuracy !== null) md.push(`**Overall accuracy:** ${a.overallAccuracy}%`);
  md.push('');

  md.push('## 2. Opening performance');
  md.push('');
  md.push('### Strongest openings');
  md.push('');
  md.push(openingTable(a.strongest));
  md.push('### Weakest openings');
  md.push('');
  md.push(openingTable(a.weakest));
  md.push('### All openings');
  md.push('');
  md.push(openingTable(a.openings));

  md.push('## 3. Results by time control');
  md.push('');
  md.push('| Time control | Games | W | D | L | Score | Avg Accuracy |');
  md.push('|---|--:|--:|--:|--:|--:|--:|');
  for (const tc of a.byTimeClass) {
    md.push(`| ${tc.timeClass} | ${wdlCells(tc.wdl)} | ${tc.avgAccuracy !== null ? tc.avgAccuracy + '%' : '—'} |`);
  }
  md.push('');

  md.push('## 4. Game-phase breakdown');
  md.push('');
  md.push('| Phase | Avg Accuracy | Inaccuracies | Mistakes | Blunders | Blunders/game | Losses decided here |');
  md.push('|---|--:|--:|--:|--:|--:|--:|');
  for (const p of a.phases) {
    md.push(
      `| ${p.phase[0].toUpperCase() + p.phase.slice(1)} | ${p.avgAccuracy !== null ? p.avgAccuracy + '%' : '—'} | ${p.inaccuracies} | ${p.mistakes} | ${p.blunders} | ${p.blundersPerGame} | ${p.decisiveErrorsInLosses} |`
    );
  }
  md.push('');
  const egTypes = Object.entries(a.patterns.endgameTypeCounts);
  if (egTypes.length) {
    md.push('### Endgame types reached');
    md.push('');
    md.push('| Endgame type | Games | W | D | L | Score |');
    md.push('|---|--:|--:|--:|--:|--:|');
    for (const [type, wdl] of egTypes.sort((x, y) => y[1].games - x[1].games)) {
      md.push(`| ${type} | ${wdlCells(wdl)} |`);
    }
    md.push('');
  }

  md.push('## 5. Tactics: strengths and misses');
  md.push('');
  md.push(`- Blunders: **${a.tactics.blundersTotal}** across ${a.analyzedCount} analyzed games`);
  md.push(`- Missed wins (winning position → advantage gone in one move): **${a.tactics.missedWins}**`);
  md.push(`- Missed forced mates: **${a.tactics.missedMates}**`);
  md.push(`- Missed tactics (engine's best was an unplayed capture/check): **${a.tactics.missedTactics}**`);
  md.push('');
  if (a.tactics.worstMoments.length) {
    md.push('### Biggest single-move swings');
    md.push('');
    md.push('| Game | Move | Played | Type | Win% before → after | Engine best |');
    md.push('|---|--:|---|---|---|---|');
    for (const { game, move } of a.tactics.worstMoments) {
      const label = `${game.white} vs ${game.black} (${game.date})`;
      md.push(
        `| ${game.site.startsWith('http') ? `[${label}](${game.site})` : label} | ${move.moveNo} | ${move.san} | ${move.kind} | ${move.winPctBefore}% → ${move.winPctAfter}% | ${move.best ?? '—'} |`
      );
    }
    md.push('');
  }

  md.push('## 6. Errors in wins vs losses');
  md.push('');
  md.push('| | Games | Inaccuracies | Mistakes | Blunders | Blunders/game |');
  md.push('|---|--:|--:|--:|--:|--:|');
  const w = a.patterns.errorsInWins, l = a.patterns.errorsInLosses;
  const per = (n: number, g: number) => (g ? Math.round((n / g) * 100) / 100 : 0);
  md.push(`| In wins | ${a.patterns.analyzedWins} | ${w.inaccuracies} | ${w.mistakes} | ${w.blunders} | ${per(w.blunders, a.patterns.analyzedWins)} |`);
  md.push(`| In losses | ${a.patterns.analyzedLosses} | ${l.inaccuracies} | ${l.mistakes} | ${l.blunders} | ${per(l.blunders, a.patterns.analyzedLosses)} |`);
  md.push('');

  md.push('## 7. Patterns detected');
  md.push('');
  if (a.patterns.narrative.length) {
    for (const n of a.patterns.narrative) md.push(`- ${n}`);
  } else {
    md.push('_Not enough analyzed games to detect reliable patterns yet — add more games over time._');
  }
  md.push('');
  if (a.patterns.lostFromWinning.length) {
    md.push('### Games where a winning position was lost');
    md.push('');
    for (const g of a.patterns.lostFromWinning) {
      const label = `${g.white} vs ${g.black}, ${g.date} — peaked at ${g.bestWinPct}% win chance` +
        (g.decisiveErrorPhase ? `, decisive error in the ${g.decisiveErrorPhase} (move ${g.decisiveErrorMove})` : '');
      md.push(`- ${g.site.startsWith('http') ? `[${label}](${g.site})` : label}`);
    }
    md.push('');
  }

  md.push('## 8. Training recommendations');
  md.push('');
  if (!a.recommendations.length) {
    md.push('_Analyze games with the engine to unlock personalized recommendations._');
  }
  for (const r of a.recommendations) {
    md.push(`### ${r.area} — priority: ${r.severity.toUpperCase()}`);
    md.push('');
    md.push(r.why);
    md.push('');
    md.push('**Puzzle themes (lichess):** ' + r.themes.map((t) => `[${t.label}](${themeUrl(t.name)})`).join(' · '));
    md.push('');
    for (const d of r.drills) md.push(`- ${d}`);
    md.push('');
  }

  md.push('## 9. Analysis history');
  md.push('');
  for (const s of meta.sessions) {
    md.push(`- ${s.date}: +${s.gamesAdded} games (${s.source})`);
  }
  md.push('');
  md.push('---');
  md.push('_To update this report later: load this .md file back into PawnPrint together with new PGN files. Already-analyzed games are kept; only new games are analyzed._');
  md.push('');

  const data: ReportData = { version: 1, meta, games };
  md.push(DATA_MARK_START);
  md.push(JSON.stringify(data));
  md.push(DATA_MARK_END);
  md.push('');
  return md.join('\n');
}

/** Extract embedded report data from a previously generated markdown file. */
export function parseMarkdownReport(text: string): ReportData | null {
  const start = text.indexOf(DATA_MARK_START);
  const end = text.indexOf(DATA_MARK_END);
  if (start === -1 || end === -1 || end <= start) return null;
  const json = text.slice(start + DATA_MARK_START.length, end).trim();
  try {
    const data = JSON.parse(json) as ReportData;
    if (data.version !== 1 || !Array.isArray(data.games)) return null;
    return data;
  } catch {
    return null;
  }
}

/** Merge older records with newly analyzed ones (new wins on id collision if it has engine data). */
export function mergeGames(oldGames: GameRecord[], newGames: GameRecord[]): GameRecord[] {
  const map = new Map<string, GameRecord>();
  for (const g of oldGames) map.set(g.id, g);
  for (const g of newGames) {
    const existing = map.get(g.id);
    if (!existing || (!existing.analyzed && g.analyzed)) map.set(g.id, g);
  }
  return [...map.values()].sort((x, y) => x.date.localeCompare(y.date));
}
